services:

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5186:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - CORS_ORIGIN=http://localhost:5173
      - FRONTEND_URL=http://localhost:5173
      - BACKEND_URL=http://localhost:5186
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:5186/api

networks:
  app-network:
    driver: bridge
      